name: Bump Major Version

on: workflow_dispatch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm version major
      - run: git push origin main --tags
